name: Redeploy Choreo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # 每 3 小时运行一次

jobs:
  Redeploy:
    name: Redeploy Choreo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4  # 最新版 checkout

      - name: 更新 README.md
        run: |
          DATE=$(date "+%Y/%m/%d %H:%M:%S")
          echo "${DATE}" > README.md
          echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: 认证 GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto deploy by Github Actions, ${{ env.DATE }}"
          branch: main
          push_options: --force

      - name: 删除旧的 Workflow 运行记录
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600

